# Spring配置
spring:
  # 数据库配置
  datasource:
    druid:
      # 主库数据源
      master:
        url: jdbc:mysql://${DB_HOST:10.10.210.19}:${DB_PORT:3306}/${DB_NAME:fast-parking-order-test}?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        username: ${DB_USERNAME:root}
        password: ${DB_PASSWORD:root}
      # 从库数据源
      slave:
        # 从数据源开关/默认关闭
        enabled: false
        url:
        username:
        password:
  # redis 配置
  redis:
    # 地址
    host: ${REDIS_HOST:10.10.210.21}
    # 端口，默认为6379
    port: ${REDIS_PORT:32114}
    # 数据库索引
    database: 0
    # 密码
    password:
