kind: Service
apiVersion: v1
metadata:
  name: payment
  namespace: parking
  labels:
    app: payment
spec:
  clusterIP: None
  ports:
    - name: http
      protocol: TCP
      port: 8100
      targetPort: 8100
    - name: http2
      protocol: TCP
      port: 9100
      targetPort: 9100
  selector:
    app: payment
  type: ClusterIP
  sessionAffinity: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: parking
  labels:
    app: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      nodeSelector:
        node-network: internet
      containers:
        - name: payment
          image: __image__
          ports:
            - containerPort: 8100
              protocol: TCP
            - containerPort: 9100
              protocol: TCP
          resources:
            limits:
              cpu: 1000m
              memory: 500Mi
            requests:
              cpu: 10m
              memory: 10Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsConfig:
        nameservers:
          - 114.114.114.114
          - 8.8.8.8
      imagePullSecrets:
        - name: parking-secret
          
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
