server:
  port: 8100

# druid spring boot 配置
druidDataSource: &druidDataSource # 别名
  type: com.alibaba.druid.pool.DruidDataSource
  driverClassName: com.mysql.cj.jdbc.Driver
  druid:
    # 初始连接数
    initialSize: 5
    # 最小连接池数量
    minIdle: 10
    # 最大连接池数量
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    # 配置一个连接在池中最大生存的时间，单位是毫秒
    maxEvictableIdleTimeMillis: 900000
    # 配置检测连接是否有效
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    webStatFilter:
      enabled: false
    statViewServlet:
      enabled: false
      # 设置白名单，不填则允许所有访问
      allow:
      url-pattern: /druid/*
      # 控制台管理用户名和密码
      login-username: ruoyi
      login-password: 123456
    filter:
      stat:
        enabled: true
        # 慢SQL记录
        log-slow-sql: true
        slow-sql-millis: 1000
        merge-sql: true
      wall:
        config:
          multi-statement-allow: true

# Spring配置
spring:
  autoconfigure:
    exclude: net.devh.boot.grpc.server.autoconfigure.GrpcServerSecurityAutoConfiguration
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: @profiles.active@ # 指定活动配置文件
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size:  10MB
      # 设置总上传的文件大小
      max-request-size:  20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # 数据库配置
  datasource:
    <<: *druidDataSource # *引用别名， << 表示合并到当前
  # redis 配置
  redis:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

# MyBatis Plus配置
mybatis-plus:
  # 搜索指定包别名
  typeAliasesPackage: com.czdx.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mybatis/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql



grpc:
  server:
    in-process-name: parking-payment-server
    # 修改服务端默认入参最大大小，默认值为4M ，这里修改为20M   20*1024*1024
    max-inbound-message-size: 20971520
    # grpc 端口号
    port: 9100
alipay:
  appId: 2016101200666723
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhdCtKaUWnT8bB4N5PimrLv+x1d7Z3noTKz/yTMp/aYhDrnaeRrQGKd8tIC7wyb8pJiCyttNKg3y1YCETTTko6x5vvvZ1uBB/7Y5BdWVqW3bm2f6ZPFvQEAVtR3tSANfpfoOiWRLeiP7p6OrSLf2wlQ1j/DMldF5EFSiima+xZblW58Vlf5jncbroO+JrFNut2BsXctB+J9Oe7l7czV5mg+UYD4tsUfRhSXRIoPe5u+26ZF6lSmhuWoLn7QJilzRxYrCtkGUg4+o4Y+hi38JBiofKGoPcWOVcMkF+65XHq0bj+HZIjtQEFlswZjYys7j+2F6rmIVQGtor7P8WnsFToQIDAQAB
  RSA_PRIVATE_KEY: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCNWwmhGDDt9g4HWpfYIZIEqJu312ywkKF/lD5ZfbF6FgtXA8zX89563NQw14DEwLLToMSB6o2KQXz1+jsuUVe+Byl95ZvdS2pmC0NHgQ2jRfIXlSfw6Ah6UO/8iSrjOWBU+uBtTJAQpnyZg66gysz3+QJ83nC+QsATG/yb87vqJZf3F5B+YOE3K6dF4rrmn8V4rCdpGqg3UPqj2LK/xST3fQzqKC6ZLGUPItVGm9oJOexZnfqUhLo1MdxyvnZB7kg+eSTF9BnBD/J41+EQ1xXyY8BsL2KrDW8y4MwuPajEGHoRqpCUbSXo/V1PT+RJuxEM3qwrDC0ponWTNK7I2/+lAgMBAAECggEACZbpelJHz3znyrvsnS751vMRTVGCACBvtFX8PNn4Fk40irypQuU6bJ9ajc2w4Kgp+Y1oh1/AJmb28UD+js/Z4fxeZjoTbtnU6ANPlyQ8Jp1yJQNraD51hMbE4R71F+Emld1HKGMPSvHgdhGm4SWg7hmof4wfneitWx6E7peEYgf83RvO4HXVHcQuJbbX5REbJI3q8SqloERvevkmjLK2iFDc9qXivw2TZO6+3bBgWiB3F6Wa/jjLiuzjutGuHRZTd+652zstnWvfL0IY8e8I/KtS7aFScP35Z79hGCPaHfX4b2PPgLF+OepTyEj0zamwZy0i0Hcjh9qATE+NDcmYKQKBgQDWwC/4j93MfxWGXsuz4emhOX5CEvxpPELKH4ezceVRdVhW6TrEYytMmXczYMjqRI5ubTMdiEwKMMrD9Q0OCPaUtcKLtA9VS0Kv6AhcNMjq7SpGjRo4OFNHSNqrDEHDXqxI8NZHw81l/qvM5LwSDX8FQiJOnfDUWj1mtgIfX60CJwKBgQCogdW+nCHLnaPlJBFKvMtRo6cSpZocucGfcx8Loo8kwHrG2FeggySJ+lOL/g0XAju3fzSzmaZVSZa761vnqP4eRa3bonmBSZwqxxeY5UTuWSh0omENS28Mhay3jxnSosw2WOXaO4zPfvU5NIZmaQDZpcvMIKEMK/s3svFNHfJrUwKBgAbrqqAYAs3USp1J8MabQSww7iCy++9oQb7BxV3DDeDSJ0alvX8Wsw6E45KES/VAwFZOrpcFDW5GpEIsY39QSqIAOYTHCLd29W81yw8tpEvt2K7tXSrypbxmXKWmf3gMVQEEweMOLFBdJKw1stniFXXV68Uc0eYGAnSM6QSZ0LmBAoGBAIxB9b4Ai4jGICOcj+AboUjE5U36FXsPiwDDe/XdSzSWGhvk+5sZTZKjkGMYBaE/NKGZ+i38GJ0o8ZRdZVRAL7TW3s3QQT7CHIDm0tdrDqMuByR9/DZqsXZE1ey76gyPgVdDS58Irj4QOOFyvOQFRrXi8O1pw2M0QJiuE3fTE3MNAoGAN3fAiEGb1tz7D+qon1r5ehw8DEp4rPOzOMXtHrLy67pMa0AHcBmtI4Fm7ZYUIoFyT6wrigOrqUSHafSsJZNlRC+KljPlhN2x3W/vIRpqmQG34tbi7qpXhEFK+w82AzNJ1N5PrzQ8/dFHotf/DXxgxuT8Um/+65KxBg1EBGOaSmQ=
