# Spring配置
spring:
  # 数据库配置
  datasource:
    druid:
      # 主库数据源
      master:
        url: jdbc:mysql://${DB_HOST:10.10.210.19}:${DB_PORT:3306}/${DB_NAME:fast-parking-test}?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        username: ${DB_USERNAME:root}
        password: ${DB_PASSWORD:root}
      # 从库数据源
      slave:
        # 从数据源开关/默认关闭
        enabled: false
        url:
        username:
        password:
  # redis 配置
  redis:
    # 地址
    host: ${REDIS_HOST:10.10.210.19}
    # 端口，默认为6379
    port: ${REDIS_PORT:30002}
    # 数据库索引
    database: 0
    # 密码
    password:
  #MQ
  rabbitmq:
    host: ${RMQ_HOST:10.10.210.20}
    port: ${RMQ_PORT:30801}
    username: ${RMQ_USERNAME:acnftest}
    password: ${RMQ_PASSWORD:acnf@admin}
    virtualHost: /

# grpc 配置
grpc:
  server:
    in-process-name: parking-lot-server
    # 修改服务端默认入参最大大小，默认值为4M ，这里修改为20M   20*1024*1024
    max-inbound-message-size: 20971520
    # grpc 端口号
    port: 9115
  client:
    # 服务端地址
    parking-device-server:
      address: 'static://${DEVICE_SERVER:device}:9085'
    parking-order-server:
      address: 'static://${ORDER_SERVER:order}:9088'
    parking-charge-server:
      address: 'static://${CHARGE_SERVER:charge}:9095'
    parking-payment-server:
      address: 'static://${PAYMENT_SERVER:payment}:9100'
    parking-notification-server:
      address: 'static://${NOTIFICATION_SERVER:notification}:9105'
    parking-member-merchant-server:
      address: 'static://${MEMBER_SERVER:10.10.210.22}:32146'

icc:
  types: car.capture,car.access
  sdk:
    host: 115.236.17.59
    port: 9021
    #icc.sdk.host=icc-dev.dahuatech.com
    clientId: dx
    clientSecret: 42bec152-8f04-476a-9aec-e7d616ff3cb3
    pwdClientId: llh
    pwdClientSecret: 42bec152-8f04-476a-9aec-e7d616ff3cb3
    username: TEST
    password: Admin123
    #icc.sdk.password=dahua2022
    grantType: password
    #icc.sdk.enable.https=false
    #icc.sdk.config.client.enable=false
    version: 1.0.0
    config:
      client:
        userId: 1

# 大华推送消息的接受地址
local:
  ip: 127.0.0.1
  port: 8080

# 关闭滑动验证
aj:
  enabled: false