kind: Service
apiVersion: v1
metadata:
  name: park-pc
  namespace: parking
  labels:
    app: park-pc
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32517
  selector:
    app: park-pc
  type: NodePort
  sessionAffinity: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: park-pc
  namespace: parking
  labels:
    app: park-pc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: park-pc
  template:
    metadata:
      labels:
        app: park-pc
    spec:
      containers:
        - name: park-pc
          image: __image__
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: 1000m
              memory: 500Mi
            requests:
              cpu: 10m
              memory: 10Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: parking-secret
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
